version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Porta padrão do AMQP para comunicação
      - "15672:15672" # Porta do painel de administração web

  cliente1:
    build: ./client
    depends_on:
      - rabbitmq
    volumes:
 
      - ./client/pasta_cliente_1:/app/pasta_cliente_1

  conversor1:
    build: ./converter
    depends_on:
      - rabbitmq

  armazenador1:
    build: ./storage
    depends_on:
      - rabbitmq
    volumes:
      - ./storage/pasta_servidor_1:/app/servidor_1