version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Porta padrão do AMQP para comunicação
      - "15672:15672" # Porta do painel de administração web

  cliente1:
    build: ./cliente
    depends_on:
      - rabbitmq
    environment:
      - NOME_PASTA_CLIENTE=pasta_cliente1
    volumes:
      - ./cliente/pasta_cliente1:/app/pasta_cliente1

  cliente2:
    build: ./cliente
    depends_on:
      - rabbitmq
    environment:
      - NOME_PASTA_CLIENTE=pasta_cliente2
    volumes:
      - ./cliente/pasta_cliente2:/app/pasta_cliente2

  conversor1:
    build: ./conversor
    depends_on:
      - rabbitmq

  conversor2:
    build: ./conversor
    depends_on:
      - rabbitmq

  armazenador1:
    build: ./armazenamento
    depends_on:
      - rabbitmq
    environment:
      - NOME_PASTA_ARMAZENAMENTO=pasta_servidor1 # 
    volumes:
      - ./armazenamento/pasta_servidor1:/app/pasta_servidor1

  armazenador2:
    build: ./armazenamento
    depends_on:
      - rabbitmq
    environment:
      - NOME_PASTA_ARMAZENAMENTO=pasta_servidor2
    volumes:
      - ./armazenamento/pasta_servidor2:/app/pasta_servidor2